version: '3.1'

services:
  db:
    image: mongo:7.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  db-dashboard:
    image: mongo-express:1-20
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/

  app:
    build:
      context: .
      target: dev
    env_file: .env
    volumes:
      - ./:/code
    ports:
      - 3000:3000
    depends_on:
      - db
